language: ruby
rvm:
- 2.2.1
before_install:
- sudo apt-get update -qq
- sudo apt-get install libqt4-dev -qq
- sudo apt-get install xvfb -qq
before_script:
- psql -c 'create role fr login createdb;' -U postgres
addons:
  postgresql: 9.3
  code_climate:
    repo_token: 9d2abe9e2bdfe62892cf37ae25ff3e825b07dad9401025adcb6f387ac82a35a8
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- DISPLAY=localhost:1.0 xvfb-run bundle exec rake spec
- bundle exec rake rubocop
- bundle exec rake teaspoon
deploy:
  provider: heroku
  api_key:
    secure: iw1rF38MIxU03c2njmliHZv0bV9XMkBeOf11pGr2OSozr6q0MJUUkg9D+E08LgHxDdUwsi9DP7U/cD81M2T9FpIUXiN8GJ/qUAM87QzaOBqwb72Ydh3QHz6uyMPRkMUarDnwFxWqovDvcpHEP+WhL3G1XGcr1b5qH9WZUFliYBA=
  app: fr-staff-app
  on:
    repo: ministryofjustice/fr-staffapp
  run:
  - rake db:migrate
