language: ruby
env:
  global:
rvm:
- 2.1.5
before_install:
- sudo apt-get update -qq
before_script:
- psql -c 'create role fr login createdb;' -U postgres
addons:
  postgresql: 9.3
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
#- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: dkfq0S/ZZ6gFYMw2xIAxb+icoA369uTdYCVQZBalAocjVax1Idfqw1eAYrBlaBJ1P8vD87H5ziYcXJnszCd+qXwlLwD86OmrtPMrpZo2kvO+2aH4zffookWMfbcH1IV6qtICjWXV3NSF5xspmj2Ho/D/CB0/HYisr9eBE9eoJls=
  app: fr-staff-app
  on:
    repo: ministryofjustice/fr-staffapp
  run:
  - "rake db:migrate"