language: ruby
sudo: false
rvm:
- 2.2.3
cache: bundler
before_script:
- psql -c 'create role fr login createdb;' -U postgres
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
addons:
  apt:
    packages:
    - xvfb
  postgresql: 9.3
  code_climate:
    repo_token: 9d2abe9e2bdfe62892cf37ae25ff3e825b07dad9401025adcb6f387ac82a35a8
script:
- bundle exec rake rubocop
- bundle exec rake db:create db:schema:load
- DISPLAY=localhost:1.0 xvfb-run bundle exec rake spec
- bundle exec rake teaspoon
