version: "3"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        source_image: 'ruby:3.2-alpine'
    depends_on:
      - db
    environment:
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      RAILS_LOG_LEVEL: info
      WAIT_HOSTS: db:5432
  db:
    image: postgres:11
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust