default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV.fetch('DB_USERNAME', nil) %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  pool: 10

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'fr-staffapp_development') %>

test: &test
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'fr-staffapp_test') %><%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || '5432' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: '<%= ENV['DB_PASSWORD'] %>'
  database: <%= ENV['DB_NAME'] || 'fr-staffapp' %>
  pool: 15
cucumber:
  <<: *test
