default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  password: '<%= ENV['DB_PASSWORD']  || '' %>'
  port: <%= ENV['DB_PORT'] || '5432' %>
  pool: 10

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'fr-staffapp_development') %>

test: &test
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'fr-staffapp_test') %><%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  password: '<%= ENV['DB_PASSWORD'] %>'
  database: <%= ENV['DB_NAME'] || 'fr-staffapp' %>
  sslmode: '<%= ENV.fetch('DB_SSL_MODE', 'disable') %>'
cucumber:
  <<: *test

