mail:
  from: no-reply@helpwithcourtfees.service.gov.uk
  reply_to: enquiries@helpwithcourtfees.dsd.io
  tech_support: helpwithfees.support@digital.justice.gov.uk
  feedback: trial-feedback@digital.justice.gov.uk
calculator:
  min_val: 1085
  uplift_per_child: 245
  couple_supp: 160
evidence_check:
  enabled: <%= ENV['EVIDENCE_CHECK_ENABLED'] || false %>
  expires_in_days: 14
payment:
  enabled: <%= ENV['PAYMENT_ENABLED'] || false %>
  expires_in_days: 14
