mail:
  from: no-reply@helpwithcourtfees.service.gov.uk
  reply_to: enquiries@helpwithcourtfees.dsd.io
  tech_support: helpwithfees@justice.gov.uk
  feedback: helpwithfees.feedback@digital.justice.gov.uk
  et:
    england_wales: ETHelpwithfees@hmcts.gsi.gov.uk
    scotland: GLASGOWET@hmcts.gsi.gov.uk
  dwp_notification_alert: <%= ENV['DWP_NOTIFICATION_ALERT_EMAILS'] %>
evidence_check:
  expires_in_days: 14
  hmrc:
    office_entity_code: <%= ENV['HMRC_OFFICE_CODE'].try(:split) || ['dig'] %>
part_payment:
  expires_in_days: 14
submission:
  token: <%= ENV['SUBMISSION_TOKEN'] %>
redirection:
  domains: <%= ENV['REDIRECTION_DOMAINS'] || '' %>
active_job:
  enabled: <%= ENV['ACTIVE_JOB_ENABLED'].present? && ['1', 'true'].include?(ENV['ACTIVE_JOB_ENABLED'].downcase) && (!ENV['APP_BUILD_TAG'].present? || !ENV['APP_BUILD_TAG'].downcase.starts_with?('jenkins-fr-staff-branch-builder')) %>
analytics:
  id: <%= ENV['GTM_ID'] || 'GTM-KZZ8ZMV' %>
savings_threshold:
  minimum_value: 3000
  maximum_value: 16000
processed_deleted:
  per_page: <%= ENV['PROCESSED_DELETED_PER_PAGE'] || 50 %>
income:
  min_threshold_base: 1170
  max_threshold_base: 5170
  per_child_increment: 265
  married_supplement: 175
child_benefits_per_month:
  1: 96
  2: 159
  3: 223
  4: 268
  5: 350
  6: 413
  7: 413
reference:
  date: <%= ENV['FIRST_SOP_REFERENCE_DATE'] || '2017-01-01' %>
fee_approval_threshold: 10000.01
sentry:
  ssl_verification: <%= ENV['SENTRY_SSL_VERIFICATION'] %>
  dsn: <%= ENV['SENTRY_DSN'] %>
personal_data_purge:
  years_ago: 7