mail:
  from: no-reply@helpwithcourtfees.service.gov.uk
  reply_to: enquiries@helpwithcourtfees.dsd.io
  tech_support: helpwithfees.support@digital.justice.gov.uk
  feedback: helpwithfees.feedback@digital.justice.gov.uk
calculator:
  min_val: 1085
  uplift_per_child: 245
  couple_supp: 160
evidence_check:
  expires_in_days: 14
part_payment:
  expires_in_days: 14
reference:
  date: <%= ENV["REFERENCE_DATE"] || '2015-12-31' %>