mail:
  from: no-reply@helpwithcourtfees.service.gov.uk
  reply_to: enquiries@helpwithcourtfees.dsd.io
  tech_support: helpwithfees.support@digital.justice.gov.uk
  feedback: helpwithfees.feedback@digital.justice.gov.uk
calculator:
  min_val: 1085
  uplift_per_child: 245
  couple_supp: 160
evidence_check:
  expires_in_days: 14
part_payment:
  expires_in_days: 14
submission:
  token: <%= ENV['SUBMISSION_TOKEN'] %>
redirection:
  domains: <%= ENV['REDIRECTION_DOMAINS'] || '' %>
active_job:
  enabled: <%= ENV['ACTIVE_JOB_ENABLED'].present? && ['1', 'true'].include?(ENV['ACTIVE_JOB_ENABLED'].downcase) && (!ENV['APP_BUILD_TAG'].present? || !ENV['APP_BUILD_TAG'].downcase.starts_with?('jenkins-fr-staff-branch-builder')) %>
analytics:
  id: <%= ENV['GA_ID'] || 'UA-37377084-54' %>
  domain: <%= ENV['GA_DOMAIN'] || 'auto' %>
savings_threshold:
  minimum: 3000
  maximum: 16000
processed_deleted:
  per_page: <%= ENV['PROCESSED_DELETED_PER_PAGE'] || 50 %>
