mail:
  from: no-reply@helpwithcourtfees.service.gov.uk
  reply_to: enquiries@helpwithcourtfees.dsd.io
  tech_support: helpwithfees.support@digital.justice.gov.uk
  feedback: helpwithfees.feedback@digital.justice.gov.uk
  et:
    england_wales: ETHelpwithfees@hmcts.gsi.gov.uk
    scotland: GLASGOWET@hmcts.gsi.gov.uk
  dwp_notification_alert:
    - dan.thompson@digital.justice.gov.uk
    - kathryn.kram@justice.gov.uk
    - sustainingteamsupport@hmcts.net
evidence_check:
  expires_in_days: 14
part_payment:
  expires_in_days: 14
submission:
  token: <%= ENV['SUBMISSION_TOKEN'] %>
redirection:
  domains: <%= ENV['REDIRECTION_DOMAINS'] || '' %>
active_job:
  enabled: <%= ENV['ACTIVE_JOB_ENABLED'].present? && ['1', 'true'].include?(ENV['ACTIVE_JOB_ENABLED'].downcase) && (!ENV['APP_BUILD_TAG'].present? || !ENV['APP_BUILD_TAG'].downcase.starts_with?('jenkins-fr-staff-branch-builder')) %>
analytics:
  id: <%= ENV['GA_ID'] || 'UA-37377084-54' %>
  domain: <%= ENV['GA_DOMAIN'] || 'auto' %>
savings_threshold:
  minimum: 3000
  maximum: 16000
processed_deleted:
  per_page: <%= ENV['PROCESSED_DELETED_PER_PAGE'] || 50 %>
income:
  min_threshold_base: 1085
  max_threshold_base: 5085
  per_child_increment: 245
  married_supplement: 160
reference:
  date: <%= ENV['FIRST_SOP_REFERENCE_DATE'] || '2017-01-01' %>
