test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>


azure:
  service: AzureStorage
  storage_account_name: <%= ENV.fetch('AZURE_STORAGE_ACCOUNT', 'hwf-test') %>
  storage_access_key: <%= ENV.fetch('AZURE_STORAGE_ACCESS_KEY', 'hwf-test-key') %>
  container: <%= ENV.fetch('AZURE_STORAGE_CONTAINER', 'private') %>
