parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- script: |
    mv .dockerignore .dockerignore.backup
    cp Dockerfile.test.dockerignore .dockerignore
    docker-compose -f docker-compose-test.yml run --rm test
    rm .dockerignore
    mv .dockerignore.backup .dockerignore
  displayName: 'Docker compose tests'