parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '$(rubyVersion)'

- script: |
    mv .dockerignore .dockerignore.backup
    cp Dockerfile.test.dockerignore .dockerignore
    docker-compose -f docker-compose-test.yml run --rm test
    rm .dockerignore
    mv .dockerignore.backup .dockerignore
  displayName: 'Docker compose tests'

- script: |
    bundle exec rubocop --fail-fast
  displayName: 'rubocop'

- script: |
    bundle exec brakeman
  displayName: 'brakeman'